### ISSUE TITLE
Transmog from another source

### ISSUE THREAD

**Issue by Sooleawa** [typicalzergling/vendor#50]
[seems i dont know how to use labels in title ]

Hello there!

I do use the "Keep: Uncollected Appearances" inbuilt rule. It helps me to save those transmog items and sell the rest. 
I would like somehow include "You have collected this appearance, but not from this item" items in the uncollected category.
Currently it sells items, that are marked by almost any other transmog addons as uncollected, because it is learned from other source.
(not everyone wants to collect transmogs from all sources, so do not scrap the current logic)

Item caught by keep rule:

![WoWScrnShot_120520_163100](https://user-images.githubusercontent.com/38173931/101247446-0a838180-371a-11eb-9d84-ed7be86b7381.jpg)

Item not caught by vendor, but i would like to send to alt later to learn:

![WoWScrnShot_120520_163113](https://user-images.githubusercontent.com/38173931/101247466-22f39c00-371a-11eb-8bf7-e737555b68e4.jpg)

**Comment by typicalzergling** [comment]
Please explain why this matters? You already have the appearance, so why do you care whether you got it from that specific item or another item that also awards that same appearance?

**Comment by Sooleawa** [comment]
All of the collecting/tmog addons i have seen yet differenciates between the 2 item types, with different tracking and warning options. These "collector modes" are for us,  collectors. I have been collecting every tmogs from every sources for years now and i hope i am not the only one.

**Comment by dkbennett** [comment]
I don't see the point, but the best way to handle a situation like this is to make an extension addon that utilizes the xmog collected/uncollected state of a dedicated transmog addon. What addon or addons for this purpose are most popular? Mog-it is the only one I know.

**Comment by Sooleawa** [comment]
Out of the ones i use
"ALL THE THINGS" - collecting
and "Can I Mog It?" - transmogging
 can surely mark them as different items

I am pretty sure allthethings is a very popular addon, and canimogit is the default suggested tmog recommended addition to go with it.

**Comment by Sooleawa** [comment]
Made rules with these,   Should work.  (Currently don't have any item to test this criteria)
![image](https://user-images.githubusercontent.com/38173931/210444290-cf637348-4353-45e1-b6a6-6608b7052327.png)
