### ISSUE TITLE
[Suggestion] IsSoulbound change back to IsBound?

### ISSUE THREAD

**Issue by sebastiantornquist** [typicalzergling/vendor#51]
C_Item.IsBound returns whether or not the item is soul- or accountbound and not just if it's soulbound.

**Comment by typicalzergling** [comment]
For rule compatibility with folks who may already be using IsSoulbound and specifically want to find that, I'm going to leave that as-is, but I think we will add IsBound to the script options in the next update.for where Soulbound or Account bound doesn't matter.

**Comment by typicalzergling** [comment]
Actually when I was looking at it, we already use C_Item.IsBound() to set IsSoulbound.

I'm just going to add IsBound as an alias for it, in case we want to make a distinction someday.
