### ISSUE TITLE
Any function for Player Name?

### ISSUE THREAD

**Issue by tflo** [typicalzergling/vendor#64]
Use-case:

Today I created a rule to trash Darkmoon tokens and Darkmoon Ride tickets, because on all my toons I do only the profession quests, which do not cost tokens, and I consume only (exactly) one Ride ticket with those toons per faire. The rest would only eat up bag space.

Except on one toon, which is the toon who does the daily DMF pet battles. I was looking for a function to exclude/include toons (i.e. something like UnitName('player')), and couldn't find anything.

Am I just blind or did you forget to add such a basic function ;-)

Edit/PS: I could help myself by excluding the toon via its class. But I have another toon of the same class, so this is just a half-way working workaround.

**Comment by umferth** [comment]
I don't think we ever thought about making a rule with a player name, but this is easy, I can add a "PlayerName" and "PlayerRealm" values.

**Comment by tflo** [comment]
Thanks, this would be great! I'm sure there are more use cases for this than the special one from my OP.

**Comment by umferth** [comment]
I just committed this to the 6.3 branch, we should have a betta available soon. - I am debating if class/race should be included as well, Thoughts?

**Comment by tflo** [comment]
Thank you!
